variable "ansible_bundle_name"             {}
variable "ansible_bundle_version"          {}
variable "aws_account_id"                  {}
variable "aws_account_short_name"          {}
variable "ebs_size"                        {}
variable "ebs_device"                      {}
variable "ebs_optimized"                   {}
variable "ebs_mountpoint"                  {}
variable "ec2_key_name"                    {}
variable "ec2_instance_profile"            {}
variable "env"                             {}
variable "jive_service"                    {}
variable "jive_subservice"                 {}
variable "jive_subservice_short_name"      {}
variable "mysql_az1_create_slaves"         {}
variable "mysql_az1_number_of_slaves"      {}
variable "mysql_az2_create_slaves"         {}
variable "mysql_az2_number_of_slaves"      {}
variable "mysql_az3_create_slaves"         {}
variable "mysql_az3_number_of_slaves"      {}
variable "mysql_create_slave_elb"          {}
variable "mysql_image_id"                  {}
variable "mysql_instance_type"             {}
variable "region"                          {}
variable "route53_data_jivehosted_zone_id" {}
variable "sla"                             {}
