variable "ansible_bundle_name"              {}
variable "ansible_bundle_version"           {}
variable "aws_account_id"                   {}
variable "aws_account_short_name"           {}
variable "ebs_device"                       {}
variable "ebs_mountpoint"                   {}
variable "ebs_optimized"                    {}
variable "ebs_size"                         {}
variable "ec2_instance_profile"             {}
variable "ec2_key_name"                     {}
variable "elasticsearch_image_id"           {}
variable "elasticsearch_instance_type"      {}
variable "env"                              {}
variable "es_master_instance_type"          {}
variable "jive_service"                     {}
variable "jive_subservice"                  {}
variable "jive_subservice_short_name"       {}
variable "kibana_ebs_optimized"             {}
variable "kibana_image_id"                  {}
variable "kibana_instance_type"             {}
variable "nginx_ebs_optimized"              {}
variable "nginx_image_id"                   {}
variable "nginx_instance_type"              {}
variable "number_of_es_azs"                 {}
variable "number_of_es_master_azs"          {}
variable "number_of_es_master_nodes_per_az" {}
variable "number_of_es_kibana_azs"          {}
variable "number_of_es_kibana_nodes_per_az" {}
variable "number_of_es_nginx_azs"           {}
variable "number_of_es_nginx_nodes_per_az"  {}
variable "number_of_es_nodes_per_az"        {}
variable "region"                           {}
variable "sla"                              {}
